### ISSUE TITLE
Categories Request

### ISSUE THREAD

**Issue by Scrum** [Akryum/awesomejs.dev#44]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when can't add to category `Jquery`, `React native`, `PostHTML`, `TypeScript`, `Rollup.js`, `RxJS`

**Describe the solution you'd like**
Add сategories `Jquery`, `React native`, `PostHTML`, `TypeScript`, `Rollup.js`, `RxJS`

**Additional context**
[PR](https://github.com/Akryum/awesomejs.dev/pull/42) for icons `PostHTML`, `jQuery`, `TypeScript`, `Rollup.js`, `RxJS`

**Comment by Akryum** [comment]
See #4 and #15
